-- MySQL Script generated by MySQL Workbench
-- Thu May 11 02:42:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AudiobookCanvasDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AudiobookCanvasDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AudiobookCanvasDB` DEFAULT CHARACTER SET utf8 ;
USE `AudiobookCanvasDB` ;

-- -----------------------------------------------------
-- Table `AudiobookCanvasDB`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AudiobookCanvasDB`.`Project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `version` VARCHAR(20) NOT NULL,
  `completed` TINYINT NOT NULL,
  `last_processed_block_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `input_file_path` VARCHAR(150) NULL,
  `output_XML_file_path` VARCHAR(150) NULL,
  `output_audiobook_path` VARCHAR(45) NULL,
  `created_on` DATETIME NOT NULL,
  `last_modified` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `last_processed_block_id_UNIQUE` (`last_processed_block_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AudiobookCanvasDB`.`Music_Track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AudiobookCanvasDB`.`Music_Track` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AudiobookCanvasDB`.`Background_Audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AudiobookCanvasDB`.`Background_Audio` (
  `id` INT NOT NULL,
  `track_id` INT NULL,
  `primary_atmosphere` VARCHAR(45) NULL,
  `secondary_atmosphere` VARCHAR(45) NULL,
  `volume` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Background_Audio_Music_Track1_idx` (`track_id` ASC) VISIBLE,
  CONSTRAINT `fk_Background_Audio_Music_Track1`
    FOREIGN KEY (`track_id`)
    REFERENCES `AudiobookCanvasDB`.`Music_Track` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AudiobookCanvasDB`.`Text_Block`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AudiobookCanvasDB`.`Text_Block` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `background_audio_id` INT NOT NULL,
  `text` VARCHAR(1500) NOT NULL,
  `generated_audio_path` VARCHAR(60) NOT NULL COMMENT '\n',
  PRIMARY KEY (`id`, `project_id`),
  UNIQUE INDEX `generated_audio_path_UNIQUE` (`generated_audio_path` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Text_Block_Project1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_Text_Block_Background_Audio1_idx` (`background_audio_id` ASC) VISIBLE,
  CONSTRAINT `fk_Text_Block_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `AudiobookCanvasDB`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Text_Block_Background_Audio1`
    FOREIGN KEY (`background_audio_id`)
    REFERENCES `AudiobookCanvasDB`.`Background_Audio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AudiobookCanvasDB`.`Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AudiobookCanvasDB`.`Character` (
  `name` VARCHAR(100) NOT NULL,
  `gender` ENUM('none', 'male', 'female') NOT NULL,
  `voice` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AudiobookCanvasDB`.`Character_Line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AudiobookCanvasDB`.`Character_Line` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text_block_id` INT UNSIGNED NOT NULL,
  `start_index` INT NOT NULL,
  `character_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `text_block_id`),
  INDEX `Character_Name_idx` (`character_name` ASC) VISIBLE,
  INDEX `fk_Character_Line_Text_Block1_idx` (`text_block_id` ASC) VISIBLE,
  CONSTRAINT `Character_Name`
    FOREIGN KEY (`character_name`)
    REFERENCES `AudiobookCanvasDB`.`Character` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Character_Line_Text_Block1`
    FOREIGN KEY (`text_block_id`)
    REFERENCES `AudiobookCanvasDB`.`Text_Block` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AudiobookCanvasDB`.`Audiobook_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AudiobookCanvasDB`.`Audiobook_Data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `book_title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `language` ENUM('en-US', 'en-UK') NOT NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id`, `project_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Audiobook_Data_Project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_Audiobook_Data_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `AudiobookCanvasDB`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AudiobookCanvasDB`.`App_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AudiobookCanvasDB`.`App_Info` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `android_version` VARCHAR(45) NULL,
  `device_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `project_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_App_Info_Project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_App_Info_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `AudiobookCanvasDB`.`Project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AudiobookCanvasDB`.`Edit_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AudiobookCanvasDB`.`Edit_History` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `line_id` INT UNSIGNED NOT NULL,
  `start_index` INT NOT NULL,
  `character_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `LineId_idx` (`line_id` ASC) VISIBLE,
  CONSTRAINT `LineId`
    FOREIGN KEY (`line_id`)
    REFERENCES `AudiobookCanvasDB`.`Character_Line` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
